export const AIList = [
  {
    type: 'generative',
    label: 'Generative AI',
    ai_list: [
      {
        type: 'generative',
        name: 'chatgpt',
        logo: '/logo/chatgpt.svg',
        label: 'ChatGPT (OpenAI)',
        description: 'Generates text and answers questions.',
        link: 'https://chatgpt.com/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'generative',
        name: 'gemini',
        logo: '/logo/gemini.svg',
        label: 'Gemini (Google)',
        description: "Google's intelligent chatbot.",
        link: 'https://gemini.google.com/app',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'generative',
        name: 'claude',
        logo: '/logo/claude.svg',
        label: 'Claude (Anthropic)',
        description: 'AI focused on safety and transparency.',
        link: 'https://claude.ai',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'generative',
        name: 'dall_e',
        logo: '/logo/dalle.png',
        label: 'DALL·E (OpenAI)',
        description: 'Creates images from text prompts.',
        link: 'https://chatgpt.com/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'generative',
        name: 'leonardo',
        logo: '/logo/leonardo.svg',
        label: 'Leonardo.ai',
        description: 'Generates creative images and videos.',
        link: 'https://leonardo.ai/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'generative',
        name: 'kling',
        logo: '/logo/kling.png',
        label: 'KLING AI',
        description:
          'Generates videos from textual descriptions or static images',
        link: 'https://klingai.com/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'generative',
        name: 'frame_drop',
        logo: '/logo/framedrop.svg',
        label: 'FRAMEDROP AI',
        description:
          'Content creators quickly extract highlights from long videos',
        link: 'https://www.framedrop.ai',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: '10web',
        logo: '/logo/10web.svg',
        label: '10Web',
        description:
          'Streamline website creation and management for WordPress.',
        link: 'https://10web.io/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'popai',
        logo: '/logo/popai.svg',
        label: 'PopAI',
        description: 'Streamline content creation and productivity tasks.',
        link: 'https://www.popai.pro/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'murf',
        logo: '/logo/murf.svg',
        label: 'MURF',
        description:
          'Text-to-speech platform that generates realistic voiceovers.',
        link: 'https://murf.ai/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'gamma',
        logo: '/logo/gamma.svg',
        label: 'Gamma AI',
        description:
          'Enables users to create stunning presentations, documents, and webpages.',
        link: 'https://gamma.app/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'runway_ml',
        logo: '/logo/runway.svg',
        label: 'Runway ML',
        description: 'AI for video creation and editing.',
        link: 'https://app.runwayml.com/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'aiva',
        logo: '/logo/aiva.png',
        label: 'AIVA',
        description: 'Composes music using AI.',
        link: 'https://www.aiva.ai/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'jasper',
        logo: '/logo/jasper.svg',
        label: 'Jasper AI',
        description: 'Automates content creation, from blogs to ads.',
        link: 'https://www.jasper.ai/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'grammarly',
        logo: '/logo/grammarly.svg',
        label: 'Grammarly',
        description: 'Grammar checking and writing enhancement.',
        link: 'https://app.grammarly.com/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'generative',
        name: 'copy',
        logo: '/logo/copy.svg',
        label: 'Copy.ai',
        description: 'Creates creative advertising content.',
        link: 'https://www.copy.ai/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'generative',
        name: 'adobe_firefly',
        logo: '/logo/firefly.svg',
        label: 'Adobe Firefly',
        description: 'AI for graphic design creativity.',
        link: 'https://firefly.adobe.com/',
        width: 100,
        height: 50,
        verify: true,
      },
    ],
  },
  {
    type: 'business',
    label: 'Business AI',
    ai_list: [
      {
        type: 'business',
        name: 'ui_path',
        logo: '/logo/uipath.svg',
        label: 'UiPath',
        description: 'Automates business workflows.',
        link: 'https://www.uipath.com/platform',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'business',
        name: 'tableau',
        logo: '/logo/tableau.svg',
        label: 'Tableau (AI features)',
        description: 'Data visualization and analytics.',
        link: 'https://www.tableau.com/products/artificial-intelligence',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'business',
        name: 'zendesk',
        logo: '/logo/zendesk.svg',
        label: 'Zendesk AI',
        description: 'Automated customer support.',
        link: 'https://www.zendesk.com/service/ai/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'business',
        name: 'intercom',
        logo: '/logo/intercom.svg',
        label: 'Intercom AI',
        description: 'Smart chatbots for businesses.',
        link: 'https://www.intercom.com/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'business',
        name: 'tldv',
        logo: '/logo/tldv.svg',
        label: 'TL;DV',
        description:
          'Record, transcribe, and summarize meetings with key moments timestamped.',
        link: 'https://tldv.io/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'business',
        name: 'orimon',
        logo: '/logo/orimon.png',
        label: 'Orimon AI',
        description:
          'Create AI-powered conversational bots for sales and customer interactions.',
        link: 'https://orimon.ai/',
        width: 100,
        height: 50,
        verify: false,
      },
    ],
  },
  {
    type: 'healthcare',
    label: 'Healthcare AI',
    ai_list: [
      {
        type: 'healthcare',
        name: 'ibm_watson_health',
        logo: '/logo/ibm.svg',
        label: 'IBM Watson Health',
        description: 'Analyzes healthcare data.',
        link: 'https://www.ibm.com/products/watsonx-assistant/healthcare',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'healthcare',
        name: 'Aidoc',
        logo: '/logo/aidoc.png',
        label: 'Aidoc',
        description: 'AI for medical imaging diagnosis.',
        link: 'https://www.aidoc.com/',
        width: 100,
        height: 50,
        verify: false,
      },
    ],
  },
  {
    type: 'entertainment',
    label: 'Entertainment AI',
    ai_list: [
      {
        type: 'entertainment',
        name: 'unity',
        logo: '/logo/unity.svg',
        label: 'Unity AI',
        description: 'AI tools for game development.',
        link: 'https://unity.com/ai',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'entertainment',
        name: 'deep_motion',
        logo: '/logo/deep.png',
        label: 'DeepMotion',
        description: 'Generates 3D motion with AI.',
        link: 'https://www.deepmotion.com/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'entertainment',
        name: 'lumen5',
        logo: '/logo/lumen5.svg',
        label: 'Lumen5',
        description: 'Converts text into videos.',
        link: 'https://lumen5.com/',
        width: 100,
        height: 50,
        verify: true,
      },
    ],
  },
  {
    type: 'research',
    label: 'Research AI',
    ai_list: [
      {
        type: 'research',
        name: 'google_deepMind',
        logo: '/logo/google.svg',
        label: 'Google DeepMind',
        description: 'Advanced AI research.',
        link: 'https://deepmind.google/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'research',
        name: 'open_ai_codex',
        logo: '/logo/chatgpt.svg',
        label: 'OpenAI Codex',
        description: 'Assists in coding and research tasks.',
        link: 'https://openai.com/index/openai-codex/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'research',
        name: 'tensorFlow',
        logo: '/logo/tensorflow.svg',
        label: 'TensorFlow',
        description: "AsGoogle's AI framework.",
        link: 'https://www.tensorflow.org/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'research',
        name: 'phind',
        logo: '/logo/phind.svg',
        label: 'Phind',
        description: 'Search engine designed for developers',
        link: 'https://www.phind.com/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'research',
        name: 'pytorch',
        logo: '/logo/pytorch.svg',
        label: 'PyTorch',
        description: 'Widely used machine learning framework.',
        link: 'https://pytorch.org/',
        width: 100,
        height: 50,
        verify: false,
      },
    ],
  },
  {
    type: 'finance',
    label: 'Finance AI',
    ai_list: [
      {
        type: 'finance',
        name: 'kavout',
        logo: '/logo/kavour.png',
        label: 'Kavout',
        description: 'Predicts stock market trends.',
        link: 'https://www.kavout.com/',
        width: 100,
        height: 50,
        verify: false,
      },
      {
        type: 'finance',
        name: 'alpaca',
        logo: '/logo/alpaca.svg',
        label: 'Alpaca',
        description: 'AI API for financial trading.',
        link: 'https://alpaca.markets/',
        width: 100,
        height: 50,
        verify: true,
      },
      {
        type: 'finance',
        name: 'mint',
        logo: '/logo/mint.svg',
        label: 'Mint AI',
        description: 'Assists in budget management.',
        link: 'https://www.mint.ai/',
        width: 100,
        height: 50,
        verify: false,
      },
    ],
  },
];
