export const AIList = [
  {
    type: 'generative',
    label: 'Generative AI',
    ai_list: [
      {
        type: 'generative',
        name: 'chatgpt',
        logo: '/logo/chatgpt.svg',
        label: 'ChatGPT (OpenAI)',
        description: 'Generates text and answers questions.',
        link: 'https://chatgpt.com/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'gemini',
        logo: '/logo/gemini.svg',
        label: 'Gemini (Google)',
        description: "Google's intelligent chatbot.",
        link: 'https://gemini.google.com/app',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'claude',
        logo: '/logo/claude.svg',
        label: 'Claude (Anthropic)',
        description: "AI focused on safety and transparency.",
        link: 'https://claude.ai',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'dall_e',
        logo: '/logo/kling.png',
        label: 'DALL·E (OpenAI)',
        description: "Creates images from text prompts.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'leonardo',
        logo: '/logo/kling.png',
        label: 'Leonardo.ai',
        description: "Generates creative images and videos.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'runway_ml',
        logo: '/logo/kling.png',
        label: 'Runway ML',
        description: "AI for video creation and editing.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'aiva',
        logo: '/logo/kling.png',
        label: 'AIVA',
        description: "Composes music using AI.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'amper_music',
        logo: '/logo/kling.png',
        label: 'Amper Music',
        description: "Creates background music for projects.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'jasper',
        logo: '/logo/kling.png',
        label: 'Jasper AI',
        description: "Automates content creation, from blogs to ads.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'grammarly',
        logo: '/logo/kling.png',
        label: 'Grammarly',
        description: "Grammar checking and writing enhancement.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'copy',
        logo: '/logo/kling.png',
        label: 'Copy.ai',
        description: "Creates creative advertising content.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'canva',
        logo: '/logo/kling.png',
        label: 'Canva AI',
        description: "Automated editing and image creation.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'generative',
        name: 'adobe_firefly',
        logo: '/logo/kling.png',
        label: 'Adobe Firefly',
        description: "AI for graphic design creativity.",
        link: '/',
        width: 100,
        height: 50,
      },
    ],
  },
  {
    type: 'business',
    label: 'Business AI',
    ai_list: [
      {
        type: 'business',
        name: 'ui_path',
        logo: '/logo/kling.png',
        label: 'UiPath',
        description: "Automates business workflows.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'business',
        name: 'blue_prism',
        logo: '/logo/kling.png',
        label: 'Blue Prism',
        description: "Robotic Process Automation (RPA) tools.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'business',
        name: 'tableau',
        logo: '/logo/kling.png',
        label: 'Tableau (AI features)',
        description: "Data visualization and analytics.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'business',
        name: 'power_bi',
        logo: '/logo/kling.png',
        description: "Business data analysis.",
        label: 'Power BI',
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'business',
        name: 'zendesk',
        logo: '/logo/kling.png',
        label: 'Zendesk AI',
        description: "Automated customer support.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'business',
        name: 'intercom',
        logo: '/logo/kling.png',
        label: 'Intercom AI',
        description: "Smart chatbots for businesses.",
        link: '/',
        width: 100,
        height: 50,
      },
    ],
  },
  {
    type: 'healthcare',
    label: 'Healthcare AI',
    ai_list: [
      {
        type: 'healthcare',
        name: 'ibm_watson_health',
        logo: '/logo/kling.png',
        label: 'IBM Watson Health',
        description: "Analyzes healthcare data.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'healthcare',
        name: 'Aidoc',
        logo: '/logo/kling.png',
        label: 'Aidoc',
        description: "AI for medical imaging diagnosis.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'healthcare',
        name: 'deep_mind',
        logo: '/logo/kling.png',
        label: 'DeepMind Health',
        description: "Google’s AI for medical research.",
        link: '/',
        width: 100,
        height: 50,
      },
    ],
  },
  {
    type: 'education',
    label: 'Education AI',
    ai_list: [
      {
        type: 'education',
        name: 'khan_academy',
        logo: '/logo/kling.png',
        label: 'Khan Academy AI (Khanmigo)',
        description: "Personalized learning guidance.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'education',
        name: 'duolingo',
        logo: '/logo/kling.png',
        label: 'Duolingo AI',
        description: "Language learning powered by AI.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'education',
        name: 'quizlet',
        logo: '/logo/kling.png',
        label: 'Quizlet AI',
        description: "Automatically generates study materials and quizzes.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'education',
        name: 'socratic',
        logo: '/logo/kling.png',
        label: 'Socratic (Google)',
        description: "AI for solving academic problems.",
        link: '/',
        width: 100,
        height: 50,
      },
    ],
  },
  {
    type: 'entertainment',
    label: 'Entertainment AI',
    ai_list: [
      {
        type: 'entertainment',
        name: 'unity',
        logo: '/logo/kling.png',
        label: 'Unity AI',
        description: "AI tools for game development.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'entertainment',
        name: 'deep_motion',
        logo: '/logo/kling.png',
        label: 'DeepMotion',
        description: "Generates 3D motion with AI.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'entertainment',
        name: 'runway',
        logo: '/logo/kling.png',
        label: 'Runway AI',
        description: "Advanced video and image editing.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'entertainment',
        name: 'lumen5',
        logo: '/logo/kling.png',
        label: 'Lumen5',
        description: "Converts text into videos.",
        link: '/',
        width: 100,
        height: 50,
      },
    ],
  },
  {
    type: 'research',
    label: 'Research AI',
    ai_list: [
      {
        type: 'research',
        name: 'google_deepMind',
        logo: '/logo/kling.png',
        label: 'Google DeepMind',
        description: "Advanced AI research.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'research',
        name: 'open_ai_codex',
        logo: '/logo/kling.png',
        label: 'OpenAI Codex',
        description: "Assists in coding and research tasks.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'research',
        name: 'tensorFlow',
        logo: '/logo/kling.png',
        label: 'TensorFlow',
        description: "AsGoogle's AI framework.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'research',
        name: 'pytorch',
        logo: '/logo/kling.png',
        label: 'PyTorch',
        description: "Widely used machine learning framework.",
        link: '/',
        width: 100,
        height: 50,
      },
    ],
  },
  {
    type: 'finance',
    label: 'Finance AI',
    ai_list: [
      {
        type: 'finance',
        name: 'kavout',
        logo: '/logo/kling.png',
        label: 'Kavout',
        description: "Predicts stock market trends.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'finance',
        name: 'alpaca',
        logo: '/logo/kling.png',
        label: 'Alpaca',
        description: "AI API for financial trading.",
        link: '/',
        width: 100,
        height: 50,
      },
      {
        type: 'finance',
        name: 'mint',
        logo: '/logo/kling.png',
        label: 'Mint AI',
        description: "Assists in budget management.",
        link: '/',
        width: 100,
        height: 50,
      },
    ],
  },
];
